language: objective-c
osx_image: xcode8
env:
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=10.0,name=iPad Pro (12.9 inch)"

before_script:
  carthage update
  KEY_CHAIN=ios-build.keychain
  security create-keychain -p travis $KEY_CHAIN
  # Make the keychain the default so identities are found
  security default-keychain -s $KEY_CHAIN
  # Unlock the keychain
  security unlock-keychain -p travis $KEY_CHAIN
  # Set keychain locking timeout to 3600 seconds
  security set-keychain-settings -t 3600 -u $KEY_CHAIN

script: xcodebuild test -project ArithmeticTools.xcodeproj -scheme ArithmeticTools -destination "${DESTINATION}" TOOLCHAINS=swift

after_success:
  - bash <(curl -s https://codecov.io/bash)
  