language: objective-c
osx_image: xcode8
env:
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=9.3,name=iPad 2" SCHEME="ArithmeticTools"
    - DESTINATION="platform=iOS Simulator,OS=10.0,name=iPad Pro (12.9 inch)" SCHEME="ArithmeticTools"
    - DESTINATION="OS X" SCHEME="ArithmeticToolsMac"

before_script: carthage update

script: travis_retry xcodebuild test 
  -project ArithmeticTools.xcodeproj 
  -scheme "${SCHEME}" 
  -destination "${DESTINATION}" 
  TOOLCHAINS=swift

after_success:
  - bash <(curl -s https://codecov.io/bash)