language: objective-c
osx_image: xcode8

before_script: carthage update

script: 

- travis_retry xcodebuild 
  -project ArithmeticTools.xcodeproj
  -scheme ArithmeticTools
  TOOLCHAINS=swift

- travis_retry xcodebuild 
  -project ArithmeticTools.xcodeproj
  -scheme ArithmeticToolsMac
  TOOLCHAINS=swift  

after_success:
  - bash <(curl -s https://codecov.io/bash)
